package com.goncharov.evgeny.chess.consts

const val TEXT_LOGO = "Saradey\nStudio"
const val TEXT_PLAYER_GAME = "Player vs Player"
const val TEXT_PLAYER_WITH_COMPUTER = "Player vs Computer"
const val TEXT_SETTINGS = "Settings"
const val TEXT_EXIT = "Exit"
const val TEXT_MENU = "Menu"
const val TEXT_BOARD_COLOR = "Board color"
const val TEXT_BOARD_COLOR_BROWN = " Board color brown"
const val TEXT_BOARD_COLOR_GRAY = " Board color gray"
const val TEXT_FIRST_MOVE_WHITE = " First move white player"
const val TEXT_FIRST_MOVE_BLACK = " First move black player"
const val TEXT_BACK = "Back"
const val TEXT_FIRST_MOVE = "The first move"