package com.goncharov.evgeny.chess.consts

const val BACKGROUND_PAPER_ID = "paper background"
const val LINE_1_ID = "line_1"
const val LINE_8_ID = "line_8"
const val LINE_7_ID = "line_7"
const val LINE_2_ID = "line_2"
const val LINE_3_ID = "line_3"
const val LINE_4_ID = "line_4"
const val LINE_5_ID = "line_5"
const val LINE_6_ID = "line_6"
const val SQUARE_GRAY_LIGHT_ID = "square gray light _1x"
const val SQUARE_GRAY_DARK_ID = "square gray dark _1x"
const val SQUARE_BROWN_LIGHT_ID = "square brown light_1x"
const val SQUARE_BROWN_DARK_ID = "square brown dark_1x"